# 02 - Axis Builder Utilities
In "Getting Started" notebook, we learned how to manually create the time axis along many
other things. Essentially, using the base `Axis` class you should be able to create different
axis for both source and destination; hence, the remapper; and finally start remappingn your
data from source axis to your destination axis.

While in previous module, you were required to perform manual calculations for the upper
and lower bound, in this module we learn how to create those axis and automatically have
those bounds calculatd for some more general cases.

## Example 0: Easier Approach to previus module example
In previous module we assumed that our source axis is a 21 day axis and our destination axis
was covering the same span of time but with weekly temporal resolution. In another word,
we were going from daily time scale to weekly time scale.


### Creating daily source axis:
To create a 21 day source time axis an easier approach would be:

In [6]:
from axisutilities import DailyTimeAxis
from datetime import date
src_axis = DailyTimeAxis(
    start_date=date(2020, 1, 1),
    n_interval=21
)

print("Source Axis: \n", src_axis)

Source Axis: 
 <timeaxis.TimeAxis>

  > nelem:
	21
  > lower_bound:
	[1577836800000000 ... 1579564800000000]
  > upper_bound:
	[1577923200000000 ... 1579651200000000]
  > data_ticks:
	[1577880000000000 ... 1579608000000000]
  > fraction:
	[0.5 ... 0.5]
  > binding:
	middle


Notes: 
- These utilities internally use micro-second passed from Jan 1st, 1970 as the unit.
If you are mixing and matching axis builder utilities with that of the manual calculation
make sure that you are using the same units and reference for all the axis
- If you want to change the default time unit, i.e. microsecond to another unit, you are
able to do that by passing a second conversion factor. For example, to use hour as your time
unit you can do the following

In [7]:
src_axis_hr = DailyTimeAxis(
    start_date=date(2020, 1, 1),
    n_interval=21,
    second_conversion_factor=(1.0 / 3600.0)
)

print("Source Axis [Hourly]: \n", src_axis_hr)

Source Axis [Hourly]: 
 <timeaxis.TimeAxis>

  > nelem:
	21
  > lower_bound:
	[438288 ... 438768]
  > upper_bound:
	[438312 ... 438792]
  > data_ticks:
	[438300 ... 438780]
  > fraction:
	[0.5 ... 0.5]
  > binding:
	middle


### Creating Weekly time axis:
Similarly, we could create the weekly time axis as follows:

In [8]:
from axisutilities import WeeklyTimeAxis
dst_axis = WeeklyTimeAxis(
    start_date=date(2020, 1, 1),
    n_interval=3
)

print("Destination Axis: \n", dst_axis)

Destination Axis: 
 <timeaxis.TimeAxis>

  > nelem:
	3
  > lower_bound:
	[1577836800000000 ... 1579046400000000]
  > upper_bound:
	[1578441600000000 ... 1579651200000000]
  > data_ticks:
	[1578139200000000 ... 1579348800000000]
  > fraction:
	[0.5 ... 0.5]
  > binding:
	middle


### Creating remapper and remapping data
Once you have the source and destination axis, the rest of the procedure is the same: you would
need to create a remapper object and then start remapping data.

In [9]:
from axisutilities import AxisRemapper
import numpy as np

remapper = AxisRemapper(from_axis=src_axis, to_axis=dst_axis)

sample_data = np.random.random((21, 90, 360))

sample_data_wkly_avg = remapper.average(sample_data)

print("Shape of remapped Sample Data: ", sample_data_wkly_avg.shape)


Shape of remapped Sample Data:  (3, 90, 360)


## Creating a Rolling window Time axis
In this example, let's assume we have the same source data and axis; however, we are 
interested to calculate a moving average with a window size of one week. There is a
utility function allowing you to do this:

In [10]:
from axisutilities import RollingWindowTimeAxis
from datetime import timedelta
rollingWindow_dst_axis = RollingWindowTimeAxis(
    start_date=date(2020, 1, 1),
    end_date=date(2020, 1, 22),
    base=timedelta(days=1),
    window_size=7
)

## Conclusions
In this module we learned how to perform the same task that we did in the first module, i.e.
creating daily and weekly time axis, without doing any manual calculations for lower and
upper bounds. Also we learned some extra utilities for creating weekly rolling window.

PLease do note that:
- we only touched the surface of the available utilities. There way more utilities available
and we are planning to add even more.
- Even for the examples, that we provided, we only show their limited capabilities. For example, 
you can change the base length of the window in the rolling window to be any unit that you want
it to be.


